/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Accounts"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Accounts", schema="dbo", catalog="DB_4TL" )
public class Accounts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Username", nullable=false, length=50)
    private String     username ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Password", nullable=false, length=60)
    private String     password ;

    @Column(name="Fullname", nullable=false, length=50)
    private String     fullname ;

    @Column(name="Email", nullable=false, length=50)
    private String     email ;

    @Column(name="Address", nullable=false, length=255)
    private String     address ;

    @Column(name="Photo", nullable=false, length=50)
    private String     photo ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="accounts")
    private List<Authorities> listOfAuthorities ; 

    @OneToMany(mappedBy="accounts")
    private List<Blogs> listOfBlogs ; 

    @OneToMany(mappedBy="accounts")
    private List<Orders> listOfOrders ; 

    @OneToMany(mappedBy="accounts")
    private List<Comments> listOfComments ; 


    /**
     * Constructor
     */
    public Accounts() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setFullname( String fullname ) {
        this.fullname = fullname ;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setPhoto( String photo ) {
        this.photo = photo ;
    }
    public String getPhoto() {
        return this.photo;
    }

    //--- GETTERS FOR LINKS
    public List<Authorities> getListOfAuthorities() {
        return this.listOfAuthorities;
    } 

    public List<Blogs> getListOfBlogs() {
        return this.listOfBlogs;
    } 

    public List<Orders> getListOfOrders() {
        return this.listOfOrders;
    } 

    public List<Comments> getListOfComments() {
        return this.listOfComments;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(username);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(photo);
        return sb.toString(); 
    } 

}
