/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Authorities"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Authorities", schema="dbo", catalog="DB_4TL" )
public class Authorities implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Username", nullable=false, length=50)
    private String     username ;

    @Column(name="RoleId", nullable=false, length=10)
    private String     roleid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="RoleId", referencedColumnName="Id", insertable=false, updatable=false)
    private Roles      roles ; 

    @ManyToOne
    @JoinColumn(name="Username", referencedColumnName="Username", insertable=false, updatable=false)
    private Accounts   accounts ; 


    /**
     * Constructor
     */
    public Authorities() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setRoleid( String roleid ) {
        this.roleid = roleid ;
    }
    public String getRoleid() {
        return this.roleid;
    }

    //--- GETTERS FOR LINKS
    public Roles getRoles() {
        return this.roles;
    } 

    public Accounts getAccounts() {
        return this.accounts;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(roleid);
        return sb.toString(); 
    } 

}
