/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "Comments"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Comments", schema="dbo", catalog="DB_4TL" )
public class Comments implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="IdBlog", nullable=false)
    private Integer    idblog ;

    @Column(name="Username", nullable=false, length=50)
    private String     username ;

    @Column(name="NoiDungCmt", length=255)
    private String     noidungcmt ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThoiGianCmt")
    private Date       thoigiancmt ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Username", referencedColumnName="Username", insertable=false, updatable=false)
    private Accounts   accounts ; 

    @ManyToOne
    @JoinColumn(name="IdBlog", referencedColumnName="id", insertable=false, updatable=false)
    private Blogs      blogs ; 


    /**
     * Constructor
     */
    public Comments() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setIdblog( Integer idblog ) {
        this.idblog = idblog ;
    }
    public Integer getIdblog() {
        return this.idblog;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setNoidungcmt( String noidungcmt ) {
        this.noidungcmt = noidungcmt ;
    }
    public String getNoidungcmt() {
        return this.noidungcmt;
    }

    public void setThoigiancmt( Date thoigiancmt ) {
        this.thoigiancmt = thoigiancmt ;
    }
    public Date getThoigiancmt() {
        return this.thoigiancmt;
    }

    //--- GETTERS FOR LINKS
    public Accounts getAccounts() {
        return this.accounts;
    } 

    public Blogs getBlogs() {
        return this.blogs;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(idblog);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(noidungcmt);
        sb.append("|");
        sb.append(thoigiancmt);
        return sb.toString(); 
    } 

}
