/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Orders", schema="dbo", catalog="DB_4TL" )
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Username", nullable=false, length=50)
    private String     username ;

    @Temporal(TemporalType.DATE)
    @Column(name="CreateDate", nullable=false)
    private Date       createdate ;

    @Column(name="Address", nullable=false, length=100)
    private String     address ;

    @Column(name="Email", nullable=false, length=50)
    private String     email ;

    @Column(name="Phone", nullable=false, length=10)
    private String     phone ;

    @Column(name="Status", nullable=false, length=100)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Username", referencedColumnName="Username", insertable=false, updatable=false)
    private Accounts   accounts ; 

    @OneToMany(mappedBy="orders")
    private List<Orderdetails> listOfOrderdetails ; 


    /**
     * Constructor
     */
    public Orders() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate ;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPhone( String phone ) {
        this.phone = phone ;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    //--- GETTERS FOR LINKS
    public Accounts getAccounts() {
        return this.accounts;
    } 

    public List<Orderdetails> getListOfOrderdetails() {
        return this.listOfOrderdetails;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
