/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="OrderDetails", schema="dbo", catalog="DB_4TL" )
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="OrderId", nullable=false)
    private Long       orderid ;

    @Column(name="ProductId", nullable=false)
    private Integer    productid ;

    @Column(name="Price", nullable=false)
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="ProductId", referencedColumnName="Id", insertable=false, updatable=false)
    private Products   products ; 

    @ManyToOne
    @JoinColumn(name="OrderId", referencedColumnName="Id", insertable=false, updatable=false)
    private Orders     orders ; 


    /**
     * Constructor
     */
    public Orderdetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setOrderid( Long orderid ) {
        this.orderid = orderid ;
    }
    public Long getOrderid() {
        return this.orderid;
    }

    public void setProductid( Integer productid ) {
        this.productid = productid ;
    }
    public Integer getProductid() {
        return this.productid;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- GETTERS FOR LINKS
    public Products getProducts() {
        return this.products;
    } 

    public Orders getOrders() {
        return this.orders;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderid);
        sb.append("|");
        sb.append(productid);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}
