/*
 * Created on 2023-04-28 ( 22:54:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entitiesForMrTu;

import java.io.Serializable;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Roles"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Roles", schema="dbo", catalog="DB_4TL" )
public class Roles implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Id", nullable=false, length=10)
    private String     id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Name", nullable=false, length=50)
    private String     name ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="roles")
    private List<Authorities> listOfAuthorities ; 


    /**
     * Constructor
     */
    public Roles() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( String id ) {
        this.id = id ;
    }
    public String getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    //--- GETTERS FOR LINKS
    public List<Authorities> getListOfAuthorities() {
        return this.listOfAuthorities;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 

}
