package com.fourTL.controller.mail.contact;

public class mail_CONSTANT {

	public String mail_order(String username, String source) {

		String welcome = "<!-- © 2018 Shift Technologies. All rights reserved. -->\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout:fixed;background-color:#f9f9f9\" id=\"bodyTable\">\r\n"
				+ "    <tbody>\r\n"
				+ "        <tr>\r\n"
				+ "            <td style=\"padding-right:10px;padding-left:10px;\" align=\"center\" valign=\"top\" id=\"bodyCell\">\r\n"
				+ "\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperBody\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableCard\" style=\"background-color:#fff;border-color:#e5e5e5;border-style:solid;border-width:0 1px 1px 1px;\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"background-color:#00d2f4;font-size:1px;line-height:3px\" class=\"topBorder\" height=\"3\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr style=\"margin-top: 1.5em;\">\r\n"
				+ "                                            <td style=\"padding-bottom: 5px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"mainTitle\">\r\n"
				+ "                                                <h2 class=\"text\" style=\"color:#000;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:28px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:36px;text-transform:none;text-align:center;padding:0;margin:0;margin-top: 1.5em;\">Hi \""+username+"\"</h2>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-bottom: 30px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"subTitle\">\r\n"
				+ "                                                <h4 class=\"text\" style=\"color:#999;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:16px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:24px;text-transform:none;text-align:center;padding:0;margin:0\">Xác nhận thanh toán thành công !</h4>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-left:20px;padding-right:20px\" align=\"center\" valign=\"top\" class=\"containtTable ui-sortable\">\r\n"
				+ "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableDescription\" style=\"\">\r\n"
				+ "                                                    <tbody>\r\n"
				+ "                                                        <tr>\r\n"
				+ "                                                            <td style=\"padding-bottom: 20px;\" align=\"center\" valign=\"top\" class=\"description\">\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">Chúc mừng bạn đã thanh toán thành công tựa game này.</p>\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">Link game của bạn.</p>\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">"+source+"</p>\r\n"
				+ "                                                            </td>\r\n"
				+ "                                                        </tr>\r\n"
				+ "                                                    </tbody>\r\n"
				+ "                                                </table>\r\n"
				+ "\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"20\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"space\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperFooter\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"footer\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px\" align=\"center\" valign=\"top\" class=\"socialLinks\">\r\n"
				+ "                                                <a href=\"#facebook-link\" style=\"display:inline-block\" target=\"_blank\" class=\"facebook\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/facebook.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#twitter-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"twitter\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/twitter.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#pintrest-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"pintrest\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/pintrest.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#instagram-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"instagram\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/instagram.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#linkdin-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"linkdin\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/linkdin.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 10px 10px 5px;\" align=\"center\" valign=\"top\" class=\"brandInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">©&nbsp;Vespro Inc. | 800 Broadway, Suite 1500 | New York, NY 000123, USA.</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 20px;\" align=\"center\" valign=\"top\" class=\"footerLinks\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\"> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">View Web Version </a>&nbsp;|&nbsp; <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Email Preferences </a>&nbsp;|&nbsp;\r\n"
				+ "                                                    <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Privacy Policy</a>\r\n"
				+ "                                                </p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 10px;\" align=\"center\" valign=\"top\" class=\"footerEmailInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">If you have any quetions please contact us <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">support@mail.com.</a>\r\n"
				+ "                                                    <br> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Unsubscribe</a> from our mailing lists</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "</table>";
		return welcome;
	}
	
	public String mail_Welcome(String username, String password) {

		String welcome = "<!DOCTYPE html\r\n"
				+ "  PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n" + "\r\n" + "<head>\r\n"
				+ "  <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "  <title>PropTech Kenya Welcome Email</title>\r\n"
				+ "  <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "    @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n" + "\r\n"
				+ "    /* Take care of image borders and formatting */\r\n" + "\r\n" + "    img {\r\n"
				+ "      max-width: 600px;\r\n" + "      outline: none;\r\n" + "      text-decoration: none;\r\n"
				+ "      -ms-interpolation-mode: bicubic;\r\n" + "    }\r\n" + "\r\n" + "    html {\r\n"
				+ "      margin: 0;\r\n" + "      padding: 0;\r\n" + "    }\r\n" + "\r\n" + "    a {\r\n"
				+ "      text-decoration: none;\r\n" + "      border: 0;\r\n" + "      outline: none;\r\n"
				+ "      color: #bbbbbb;\r\n" + "    }\r\n" + "\r\n" + "    a img {\r\n" + "      border: none;\r\n"
				+ "    }\r\n" + "\r\n" + "    /* General styling */\r\n" + "\r\n" + "    td,\r\n" + "    h1,\r\n"
				+ "    h2,\r\n" + "    h3 {\r\n" + "      font-family: Helvetica, Arial, sans-serif;\r\n"
				+ "      font-weight: 400;\r\n" + "    }\r\n" + "\r\n" + "    td {\r\n"
				+ "      text-align: center;\r\n" + "    }\r\n" + "\r\n" + "    body {\r\n"
				+ "      -webkit-font-smoothing: antialiased;\r\n" + "      -webkit-text-size-adjust: none;\r\n"
				+ "      width: 100%;\r\n" + "      height: 100%;\r\n" + "      color: #666;\r\n"
				+ "      background: #fff;\r\n" + "      font-size: 16px;\r\n" + "      height: 100vh;\r\n"
				+ "      width: 100%;\r\n" + "      padding: 0px;\r\n" + "      margin: 0px;\r\n" + "    }\r\n" + "\r\n"
				+ "    table {\r\n" + "      border-collapse: collapse !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .headline {\r\n" + "      color: #444;\r\n" + "      font-size: 36px;\r\n" + "    }\r\n" + "\r\n"
				+ "    .force-full-width {\r\n" + "      width: 100% !important;\r\n" + "    }\r\n" + "  </style>\r\n"
				+ "  <style media=\"screen\" type=\"text/css\">\r\n" + "    @media screen {\r\n" + "\r\n"
				+ "      td,\r\n" + "      h1,\r\n" + "      h2,\r\n" + "      h3 {\r\n"
				+ "        font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
				+ "      }\r\n" + "    }\r\n" + "  </style>\r\n"
				+ "  <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
				+ "    /* Mobile styles */\r\n" + "    @media only screen and (max-width: 480px) {\r\n" + "\r\n"
				+ "      table[class=\"w320\"] {\r\n" + "        width: 320px !important;\r\n" + "      }\r\n"
				+ "    }\r\n" + "  </style>\r\n" + "  <style type=\"text/css\"></style>\r\n" + "\r\n" + "</head>\r\n"
				+ "\r\n" + "<body bgcolor=\"#fff\" class=\"body\"\r\n"
				+ "  style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
				+ "  <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
				+ "    <tbody>\r\n" + "      <tr>\r\n"
				+ "        <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
				+ "          <center class=\"\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
				+ "              <tbody>\r\n" + "                <tr>\r\n"
				+ "                  <td align=\"center\" class=\"\" valign=\"top\">\r\n"
				+ "                    <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
				+ "                    </table>\r\n"
				+ "                    <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                      style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
				+ "                      <tbody style=\"margin-top: 15px;\">\r\n"
				+ "                        <tr class=\"\">\r\n" + "                          <td class=\"\">\r\n"
				+ "                            <img alt=\"robot picture\" width=\"350\"\r\n"
				+ "                              src=\"https://lh3.googleusercontent.com/pw/AMWts8BE52AhhQd3jDG4W2RUxzaAq69PcixOhv_nV9VI2IxljwxzDHr6XShIYlSfq1io_5IdAJNePdcUHIDRzYcMJZFaYKf7N4e39CVIwWjUOcjVcW1ra2A4_oecW0PLytJyocXmFFNRAAtQQymNTGxxWD0=w960-h326\">\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr class=\"\">\r\n"
				+ "                          <td class=\"headline\">Welcome to 4TL Shop!</td>\r\n"
				+ "                        </tr>\r\n" + "                        <tr>\r\n"
				+ "                          <td>\r\n" + "                            <center class=\"\">\r\n"
				+ "                              <table cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"margin: 0 auto;\" width=\"75%\">\r\n"
				+ "                                <tbody class=\"\">\r\n"
				+ "                                  <tr class=\"\">\r\n"
				+ "                                    <td class=\"\" style=\"color:#444; font-weight: 400;\"><br><br>\r\n"
				+ "                                      Bạn đã được đăng ký thành công tài khoản shop.<br>\r\n"
				+ "                                      <br>\r\n"
				+ "                                      Thông tin đăng nhập của bạn được cung cấp dưới đây:\r\n"
				+ "                                      <br> <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">Username: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">" + username
				+ "</span>\r\n" + "                                      <br>\r\n"
				+ "                                      <span style=\"font-weight:bold;\">Password: &nbsp;</span><span\r\n"
				+ "                                        style=\"font-weight:lighter;\" class=\"\">" + password
				+ "</span>\r\n" + "                                      <br><br>\r\n"
				+ "                                      <br>\r\n" + "                                    </td>\r\n"
				+ "                                  </tr>\r\n" + "                                </tbody>\r\n"
				+ "                              </table>\r\n" + "                            </center>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr>\r\n" + "                          <td class=\"\">\r\n"
				+ "                            <div class=\"\">\r\n"
				+ "                              <a style=\"background-color:#EBB000;border-radius:4px;color:#000000;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:18px;font-weight:normal;line-height:50px;text-align:center;text-decoration:none;width:350px;-webkit-text-size-adjust:none;\"\r\n"
				+ "                                href=\"#\">Truy cập tài khoản và bắt đầu trải nghiệm</a>\r\n"
				+ "                            </div>\r\n" + "                            <br>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                      </tbody>\r\n" + "\r\n" + "                    </table>\r\n" + "\r\n"
				+ "                    <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                      style=\"margin: 0 auto; margin-bottom: 5px:\">\r\n"
				+ "                      <tbody>\r\n" + "                        <tr>\r\n"
				+ "                          <td class=\"\" style=\"color:#444;\r\n" + "                    \">\r\n"
				+ "                            <p>Mật khẩu đã được tạo tự động, tuy nhiên hãy thay đổi nó ở\r\n"
				+ "\r\n"
				+ "                              <a href=\"#\" style=\"text-decoration: underline; color: blue;\">\r\n"
				+ "                                đây</a>\r\n" + "\r\n" + "                            </p>\r\n"
				+ "                          </td>\r\n" + "                        </tr>\r\n"
				+ "                      </tbody>\r\n" + "                    </table>\r\n"
				+ "                  </td>\r\n" + "                </tr>\r\n" + "              </tbody>\r\n"
				+ "            </table>\r\n" + "          </center>\r\n" + "        </td>\r\n" + "      </tr>\r\n"
				+ "    </tbody>\r\n" + "  </table>\r\n" + "</body>\r\n" + "\r\n" + "</html>";
		return welcome;
	}


}
